name: Deploy Fullstack App to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 15m
          script: |
            cd ~
            if [ -d "Ganymede" ]; then
              cd Ganymede && git pull
            else
              git clone https://github.com/Ashutoshxo/Ganymede.git Ganymede
              cd Ganymede
            fi
            
            # Create Swap memory (0 Extra Cost)
            if [ ! -f /swapfile ]; then
              sudo fallocate -l 2G /swapfile
              sudo chmod 600 /swapfile
              sudo mkswap /swapfile
              sudo swapon /swapfile
            fi

            docker compose down || true
            docker compose up --build -d